version: '3'
services: 
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node-modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_HOST=postgres
            - PG_DB=postgres
            - PG_PWD=postgres_password
            - PG_PORT=5432
    worker:
        build: 
            context: ./worker
            dockerfile: Dockerfile.dev
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - "5000:80"